export const HEADER_SET_TITLE = 'HEADER_SET_TITLE';

export const ARTICLE_FETCHING_START = 'ARTICLE_FETCHING_START';
export const ARTICLE_FETCHING_ERROR = 'ARTICLE_FETCHING_ERROR';
export const ARTICLE_FETCHING_FILL = 'ARTICLE_FETCHING_FILL';

export const COMMENT_FETCHING_START = 'COMMENT_FETCHING_START';
export const COMMENT_FETCHING_ERROR = 'COMMENT_FETCHING_ERROR';
export const COMMENT_FETCHING_SUCCESS = 'COMMENT_FETCHING_SUCCESS';

export const COMMENT_ADDING_START = 'COMMENT_ADDING_START';
export const COMMENT_ADDING_ERROR = 'COMMENT_ADDING_ERROR';
export const COMMENT_ADDING_SUCCESS = 'COMMENT_ADDING_SUCCESS';
